import { useNavigate } from 'react-router-dom'
import { ArrowLeft, FileText } from 'lucide-react'
import Navbar from '../components/layout/Navbar/Navbar.js'
import Footer from '../components/layout/Footer.js'

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div className="mb-8">
    <h2 className="text-lg font-bold text-slate-900 dark:text-white mb-3">{title}</h2>
    <div className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed space-y-2">
      {children}
    </div>
  </div>
)

function TermsOfService() {
  const navigate = useNavigate()

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 flex flex-col">
      <Navbar />

      <main className="flex-1 max-w-3xl mx-auto w-full px-4 md:px-8 py-12">
        {/* Header */}
        <button
          onClick={() => navigate(-1)}
          className="flex items-center gap-1.5 text-sm font-medium text-slate-500 dark:text-slate-400 hover:text-brand-purple dark:hover:text-brand-purple-light transition-colors mb-8"
        >
          <ArrowLeft size={16} /> Back
        </button>

        <div className="flex items-center gap-4 mb-10">
          <div className="w-12 h-12 rounded-2xl bg-linear-to-br from-brand-purple to-brand-indigo flex items-center justify-center shadow-lg shadow-brand-purple/30 shrink-0">
            <FileText size={22} className="text-white" />
          </div>
          <div>
            <h1 className="text-3xl font-black text-slate-900 dark:text-white">Terms of Service</h1>
            <p className="text-sm text-slate-500 dark:text-slate-500 mt-0.5">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900/60 rounded-2xl border border-slate-200/60 dark:border-white/5 p-8">

          <Section title="1. Acceptance of Terms">
            <p>By accessing or using NewsSummarizer ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
          </Section>

          <Section title="2. Description of Service">
            <p>NewsSummarizer is a news aggregation platform that collects articles from public RSS feeds and provides AI-generated summaries. The Service is provided free of charge for personal, non-commercial use.</p>
          </Section>

          <Section title="3. User Accounts">
            <p>To access certain features (saving summaries, unlimited AI summaries), you must create an account. You are responsible for:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Maintaining the confidentiality of your password</li>
              <li>All activity that occurs under your account</li>
              <li>Providing accurate and up-to-date information</li>
            </ul>
            <p className="mt-2">We reserve the right to terminate accounts that violate these terms.</p>
          </Section>

          <Section title="4. AI-Generated Summaries">
            <p>Summaries are generated by OpenAI's GPT-4o-mini model and are provided for informational purposes only. We do not guarantee the accuracy, completeness, or timeliness of any AI-generated content. Always refer to the original source article for full context.</p>
          </Section>

          <Section title="5. Usage Limits">
            <p>To ensure fair access for all users, the following rate limits apply:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li><strong className="text-slate-700 dark:text-slate-300">Guest users:</strong> 2 AI summaries per 24-hour period</li>
              <li><strong className="text-slate-700 dark:text-slate-300">Registered users:</strong> 10 AI summaries per 24-hour period</li>
            </ul>
            <p className="mt-2">Attempting to circumvent these limits (e.g. creating multiple accounts) is a violation of these terms.</p>
          </Section>

          <Section title="6. Intellectual Property">
            <p>News articles displayed on the Service remain the property of their respective publishers. NewsSummarizer does not claim ownership of any third-party content. AI-generated summaries are derivative works created for personal use only and should not be republished without permission.</p>
          </Section>

          <Section title="7. Prohibited Conduct">
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to gain unauthorised access to any part of the Service</li>
              <li>Scrape, crawl, or systematically extract data from the Service</li>
              <li>Use automated tools to generate summaries in bulk</li>
              <li>Redistribute AI-generated summaries commercially</li>
            </ul>
          </Section>

          <Section title="8. Disclaimer of Warranties">
            <p>The Service is provided "as is" without warranties of any kind. We do not warrant that the Service will be uninterrupted, error-free, or that news content will be current or accurate. News articles are sourced from third-party RSS feeds and we are not responsible for their content.</p>
          </Section>

          <Section title="9. Limitation of Liability">
            <p>To the fullest extent permitted by law, NewsSummarizer shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service, including reliance on AI-generated summaries.</p>
          </Section>

          <Section title="10. Changes to Terms">
            <p>We reserve the right to update these terms at any time. Continued use of the Service after changes are posted constitutes acceptance of the revised terms. We will indicate the last updated date at the top of this page.</p>
          </Section>

          <Section title="11. Contact">
            <p>If you have any questions about these Terms, please reach out via the <a href="https://github.com/Chisomworlu12" target="_blank" rel="noopener noreferrer" className="text-brand-indigo dark:text-brand-purple-light hover:underline font-medium">GitHub profile</a>.</p>
          </Section>

        </div>
      </main>

      <Footer />
    </div>
  )
}

export default TermsOfService
